language: python

python:
  - "3.5"

env:
    - TOX_ENV=py36-django19
    - TOX_ENV=py35-django19
    - TOX_ENV=py34-django19
    - TOX_ENV=py36-django110
    - TOX_ENV=py35-django110
    - TOX_ENV=py34-django110

install:
  - pip install -r requirements.txt
  - pip install tox

script:
  - tox -e $TOX_ENV
