# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilonull', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
